const darkTheme = {
  '@primary-color': '#00aEa1',
  '@info-color': '#b211b2',
  '@warning-color': '#c1a412',
  '@success-color': '#88c41a',
  '@highlight-color': '#a8071a',
  '@body-background': '#000000',
  '@component-background': '#000001',
  '@heading-color': '#fffffc',
  '@text-color': '#fffffc',
  '@text-color-secondary': "#cccccc",
  '@border-color-base': '#828383',
  '@border-color-split': '#363636',
  '@error-color': '#f5222d', 
  '@timeline-color': '#dea3e9',
  '@layout-body-background': '#000000',
  '@layout-header-background': '#00000075',
  '@layout-sider-background': '#292929',
  '@layout-trigger-background': '#313232',
  '@layout-trigger-color': '#292929',
  '@disabled-color': '#828383',
  '@background-color-light': '#1890ff',
  '@background-color-base': '#262626',
  '@item-active-bg': '#1890ff',
  '@item-hover-bg': '#214423',
  '@btn-default-bg': '#292929',
  '@input-bg': '#313232',
  '@popover-bg': '#262629',
  '@menu-dark-submenu-bg': '#00000077',
  '@table-header-bg': '#636363',
  '@table-row-hover-bg': '#8C8C8C',
  '@table-selected-row-bg': '#236634',
  '@table-expanded-row-bg': '#8C8C8C',
  '@tag-default-bg': '#262628',
  '@collapse-header-bg': '#262629',
  '@card-head-color': '#fffffc',
  '@card-head-background': '000000',
  '@card-actions-background': '#636363',
  '@card-background': '#292929',
  '@modal-mask-bg': 'fade(#292929, 45%)',
  '@rate-star-color': '#00aEa1'
};
  
const lightTheme = {
  '@primary-color': '#2046f0',
  '@info-color': '#221088',
  '@warning-color': '#ffee07',
  '@success-color': '#88c41a',
  '@highlight-color': '#f5222d',
  '@body-background': '#fffffe',
  '@component-background': '#fffffd',
  '@heading-color': '#000000',
  '@text-color': '#000001',
  '@text-color-secondary': "#222222",
  '@border-color-base': '#d9d9d9',
  '@border-color-split': '#d9d0d9',
  '@error-color': '#f5222d', 
  '@timeline-color': '#dea3e9',
  '@layout-body-background': '#ffffff',
  '@layout-header-background': '#00000075',
  '@layout-sider-background': '#001529',
  '@layout-trigger-background': '#002140',
  '@layout-trigger-color': '#fffffc',
  '@disabled-color': '#000004',
  '@background-color-light': '#fffffe',
  '@background-color-base': '#fffffc',
  '@item-active-bg': '#1890fe',
  '@item-hover-bg': '#1890fd',
  '@btn-default-bg': '#fffffa',
  '@input-bg': '#ffffff',
  '@popover-bg': '#fffffe',
  '@menu-dark-submenu-bg': '#00000077',
  '@table-header-bg': '#d9d5d9',
  '@table-row-hover-bg': '#fffffe',
  '@table-selected-row-bg': '#1890ff',
  '@table-expanded-row-bg': '#fbfbfb',
  '@tag-default-bg': '#fffffe',
  '@collapse-header-bg': '#fffffc',
  '@card-head-color': '#000009',
  '@card-head-background': '#fffffe',
  '@card-actions-background': '#fffffd',
  '@card-background': '#fffffd',
  '@modal-mask-bg': 'fade(#292929, 45%)',
  '@rate-star-color': "#2046f0"
};

const icons = ["vibrant", "green", "white", "black", 
              "red", "yellow", "pink", "ocean", 
              "warm", "neon", "deepBlue", "gradient", 
              "blue", "orange", "abstract", "violet", 
              "gold", "galaxy", "vector"]

export { darkTheme, lightTheme, icons };